#!/bin/sh -x
#
#  Authors:
#    Christian Schulte <schulte@ps.uni-sb.de>
#
#  Copyright:
#    Christian Schulte, 1998
#
#  Last change:
#    $Date$ by $Author$
#    $Revision$
#
#  This file is part of Mozart, an implementation
#  of Oz 3:
#     http://www.mozart-oz.org
#
#  See the file "LICENSE" or
#     http://www.mozart-oz.org/LICENSE.html
#  for information on usage and redistribution
#  of this file, and for a DISCLAIMER OF ALL
#  WARRANTIES.
#

RPMROOT=/usr/src/redhat
RPMSRC=$RPMROOT/SOURCES
RPMSPEC=$RPMROOT/SPECS
TMPDIR=/tmp

#
# Read dir
#
if test $# -lt 2
then
   echo "usage: create-rpm <src-dir> <dst-dir>" 1>&2;
   exit 1;
fi
BUILDDIR=$1
SRCTAR=`ls ${BUILDDIR}/mozart-*.*-src.tar.gz`
DOCTAR=`ls ${BUILDDIR}/mozart-*.*-doc.tar.gz`
DSTDIR=$2
OZHOME=/usr/lib/mozart

#
# Find version
#

VERSION=`(echo ${SRCTAR} | sed 's/.*mozart-\(.*\..*\)-src.tar.gz/\1/')`
BUILD=`(echo $Revision$ | sed 's|.*\.\([1-9][0-9]*\).*|\1|')`

#
# Build sh files
#

cd $TMPDIR

cat > oz.sh <<EOF
export PATH=${OZHOME}/bin:\${PATH}
EOF

cat > oz.csh <<EOF
setenv PATH ${OZHOME}/bin:\${PATH}
EOF

chmod a+x oz.sh oz.csh
tar cf - oz.csh oz.sh | gzip -9 -c > ${RPMSRC}/mozart-profiles.tar.gz
rm -f oz.sh oz.csh


#
# Build xpm
#

cat > ${RPMSRC}/mozart.xpm <<EOF
/* XPM */
static char * mozart_xpm[] = {
"69 30 32 1",
"       c None",
".      c #FFFFFF",
"+      c #FFE69E",
"@      c #FBF6E9",
"#      c #F7E7B8",
"\$     c #FAD466",
"%      c #FBCE4A",
"&      c #FFDE7C",
"*      c #FFF3D2",
"=      c #F0D688",
"-      c #E3BA42",
";      c #61501F",
">      c #100F0A",
",      c #000000",
"'      c #392E0F",
")      c #B29030",
"!      c #777777",
"~      c #484848",
"{      c #A7A7A7",
"]      c #282828",
"^      c #D7D7D7",
"/      c #201B08",
"(      c #A18F59",
"_      c #8F8F8F",
":      c #896F25",
"<      c #725C1E",
"[      c #D3AC3E",
"}      c #C0B185",
"|      c #514215",
"1      c #606060",
"2      c #BFBFBF",
"3      c #C2A34C",
"                                #@                                   ",
"                              *\$%&                                   ",
"                            *&&*%%*                                  ",
"                           +\$*  #%\$                                  ",
"                         #\$#    #%%#                                 ",
"                       *\$&      #%%%                                 ",
"                     @=%%\$  #=  +%%%+                                ",
"                    #%%%%%=\$%#  &%%%%*                               ",
"                  #-;>,')%%%%#  \$%%+%&                         !~~   ",
"                *&)>,,,,,;%%%*  %=@ &%*                        ~,,   ",
"              @+%%>,')',,,)%%*  *   #%\$                        ~,,   ",
"~~~{],]_^~,,~@+%%),,)%%/,,/%%     @(>[%#      _],,>~^  !~~!>~_~>,,~~ ",
",,,,,,,,>,,,,~@%%:,,<%%[,,,[%    }',,|%%@    1,,,,,,>^ ~,,,,~!,,,,,, ",
",,,]!>,,,!~,,, #%:,,>%%%',,[%# #;,,,,'%%+   ^,,>{^],,_ ~,,,,~_~,,,~~ ",
",,,2 !,,1 @,,,  \$[,,,;%%:,,[%%3>,,>,,<%%%*  @2!2 ^],,! ~,,>{   ,,,   ",
",,,2 !,,!  ,,,  #%|,,,:[',/%%%%/>)[,,:%%%&   @!],,,,,! ~,,!    ,,,   ",
",,,  !,,!  ,,,   &%/,,,,,,)\$%%%[%%),,)%%%%# @>,,]1],,! ~,,_    ,,,   ",
",,,  !,,!  ,,,   *%%',,,~2   #%%%%:,,[%%:%\$ _,,]@ ~,,! ~,,2    ,,,   ",
",,,  !,,!  ,,,    +%%[[=      *%%%;,,[:>,:%#!,,~ ^>,,! ~,,2    ,,,_2@",
",,,  !,,!  ,,,     %%%%  *&#   #%%',,/,,,:\$*_,,,],,,,! ~,,2    ],,,,2",
",,,  !,,!  ,,,     #%%=  #%%*   %%/,,,,'3#   ~,,,~!,,! ~,,2    {>,,,2",
"                    \$%#  #%%\$   =%/,,/)=@     ^2^                22^ ",
"                    *%&   \$%%#  #%)>:\$*                              ",
"                     &%   *%%+  &%%-#                                ",
"                     *%#   *=*  %%+                                  ",
"                      +%*      =&@                                   ",
"                       %%#   *+*                                     ",
"                       #%%%%%#                                       ",
"                        \$%%+                                         ",
"                        *&*                                          "};
EOF

cp ${SRCTAR} ${DOCTAR} ${RPMSRC}

# Generate redhat spec file
cd $TMPDIR
cat > ${RPMSPEC}/mozart-$VERSION-$BUILD.spec <<EOF
# Spec file for Mozart, an efficient and distributed implementation of Oz
# Author: Christian Schulte, 1998
# Copyright: Christian Schulte, 1998
Name: mozart
Version: ${VERSION}
Release: ${BUILD}
Summary: Mozart, an efficient and distributed implementation of Oz
Copyright: BSD (similar)
Vendor: Programming Systems Lab Saarbrücken
Url: http://www.mozart-oz.org/
Group: Development/Languages
Packager: Christian Schulte <schulte@ps.uni-sb.de>
Icon: mozart.xpm

Source0: mozart-${VERSION}-src.tar.gz
Source1: mozart-${VERSION}-doc.tar.gz
Source2: mozart-profiles.tar.gz

BuildRoot: /var/tmp/mozart-${VERSION}

%description
The Mozart system provides state-of-the-art support in two areas: open
distributed computing and constraint-based inference. Mozart
implements Oz, a concurrent object-oriented language with dataflow
synchronization. Oz combines concurrent and distributed programming
with logical constraint-based inference, making it a unique choice for
developing multi-agent systems. Mozart is an ideal platform for both
general-purpose distributed applications as well as for hard problems
requiring sophisticated optimization and inferencing abilities. We
have developed applications in scheduling and time-tabling, in
placement and configuration, in natural language and knowledge
representation, multi-agent systems and sophisticated collaborative
tools.

Mozart has been jointly developed by the Programming Systems Lab at
DFKI and Universität des Saarlandes, the Swedish Institute of Computer
Science, and Université de Louvain.

This package contains all you need to run and develop Oz programs with
Mozart.
%package doc
Summary: Mozart documentation
Group: Development/Languages
requires: mozart
%description doc
This package contains the extensive Mozart online documentation as a set of
HTML pages. It also contains demo applications that can directly be
started from the pages.
%package contrib
Summary: Mozart contributions
Group: Development/Languages
requires: mozart
%description contrib
This package contains a collection of contributed software packages
fro Mozart that might come in handy for applications like a regular
expression package, data base interfaces, and so on.
%prep
rm -rf \$RPM_BUILD_DIR/mozart-${VERSION}
%setup -c -D -T -a 0
mkdir tmp-doc
cd tmp-doc
gzip -dc \$RPM_SOURCE_DIR/mozart-${VERSION}-doc.tar.gz | tar xf -
mv mozart/doc ..
cd ..
chown -R root .
chgrp -R root .
chmod -R a+rX,g-w,o-w .
rm -rf tmp-doc
%setup -c -D -T -a 2

%build
cd mozart
: \${CFLAGS="\$RPM_OPT_FLAGS"} && \
: \${CXXFLAGS="\$RPM_OPT_FLAGS"} && \
export CFLAGS && export CXXFLAGS && \
./configure --prefix=\$RPM_BUILD_ROOT$OZHOME

make

%install
PREFIX=\$RPM_BUILD_ROOT$OZHOME
rm -rf \$PREFIX
mkdir -p \$PREFIX
# install docs
rm -rf doc/demo/applets
cp -a doc \$PREFIX
# Generic install
(cd mozart && make install)

# With this installation stripping works fine

%ifarch i386

(cd \$PREFIX/platform/linux-i486 && \
        strip *.exe && \
        strip *.so )

(cd \$PREFIX/contrib && \
        strip ./*/*.so-linux-i486 && \
        strip *.so-linux-i486 )

%endif

# config files
mkdir -p \$RPM_BUILD_ROOT/etc/profile.d
cp -a oz.sh oz.csh \$RPM_BUILD_ROOT/etc/profile.d

%clean
rm -rf \$RPM_BUILD_ROOT
%files
%doc mozart/README mozart/LICENSE mozart/LICENSE.html
%config /etc/profile.d/oz.sh
%config /etc/profile.d/oz.csh
$OZHOME/LICENSE
$OZHOME/LICENSE.html
$OZHOME/bin
$OZHOME/cache
$OZHOME/include
$OZHOME/platform
$OZHOME/share
%files doc
$OZHOME/doc
$OZHOME/examples
%files contrib
$OZHOME/contrib
EOF

#
# No we have all what we need, go and build rpms
#

rpm -ba --clean ${RPMSPEC}/mozart-$VERSION-$BUILD.spec
rm -f ${RPMSPEC}/mozart-$VERSION-$BUILD.spec
rm -f ${RPMSRC}/mozart-$VERSION.tar.gz
rm -f ${RPMSRC}/mozart-doc-$VERSION.tar.gz
rm -f ${RPMSRC}/mozart-profiles.tar.gz

#
# Move the created rpms to destination
#

mv ${RPMROOT}/RPMS/i386/mozart-{,doc-,contrib-}$VERSION-$BUILD.i386.rpm ${DSTDIR}
mv ${RPMROOT}/SRPMS/mozart-$VERSION-$BUILD.src.rpm ${DSTDIR}
