makefile(
   uri     : 'x-oz://system/wp'
   depends : o(
		'QTk.ozf'
		: ['QTkFrame.ozf' 'QTkBare.ozf' 'QTkDevel.ozf' 'QTkImage.ozf' 'QTkMenu.ozf'
		   'QTkSpace.ozf' 'QTkLabel.ozf' 'QTkButton.ozf' 'QTkCheckbutton.ozf'
		   'QTkRadiobutton.ozf' 'QTkScale.ozf' 'QTkScrollbar.ozf' 'QTkEntry.ozf'
		   'QTkCanvas.ozf' 'QTkListbox.ozf' 'QTkText.ozf' 'QTkPlaceholder.ozf' 'QTkGrid.ozf'
		   'QTkPanel.ozf' 'QTkRubberframe.ozf' 'QTkScrollframe.ozf' 'QTkToolbar.ozf'
		   'QTkDropdownlistbox.ozf' 'QTkNumberentry.ozf'
		   'PrintCanvas.ozf' 'TkTranslator.ozf']
		'QTkBare.ozf'
		: ['QTk.oz' 'QTkClipboard.oz' 'QTkFont.oz' 'QTkDialogbox.oz'
		   'QTkFrame.oz']
                'TkTranslator.ozf'
                : ['TkTranslator.oz' 'utf2iso.dat']
		'QTkDropdownbutton_bitmap.ozf'
		: ['QTkImageLibBoot.ozf' 'mini-down.xbm']
		'QTkDropdownlistbox.ozf'
		: ['QTkDropdownbutton_bitmap.ozf']
		'QTkNumberentry.ozf'
		: ['QTkNumberentry_bitmap.ozf']
		'QTkNumberentry_bitmap.ozf'
		: ['QTkImageLibBoot.ozf' 'mini-inc.xbm' 'mini-dec.xbm']
		'Prototyper.ozf'
		: ['PrototyperData/Advanced_01_Toplevel.nfo'
		   'PrototyperData/Advanced_01_Toplevel.oz'
		   'PrototyperData/Advanced_02_Tooltips.nfo'
		   'PrototyperData/Advanced_02_Tooltips.oz'
		   'PrototyperData/Advanced_03_TclTk.nfo'
		   'PrototyperData/Advanced_03_TclTk.oz'
		   'PrototyperData/Advanced_04_Tk_module.nfo'
		   'PrototyperData/Advanced_04_Tk_module.oz'
		   'PrototyperData/Advanced_05_Aliases.nfo'
		   'PrototyperData/Advanced_05_Aliases.oz'
		   'PrototyperData/Click_here_to_begin.nfo'
		   'PrototyperData/Click_here_to_begin.oz'
		   'PrototyperData/Demo_01_Snake.nfo'
		   'PrototyperData/Demo_01_Snake.oz'
		   'PrototyperData/Demo_02_ThisApp.nfo'
		   'PrototyperData/Demo_02_ThisApp.oz'
		   'PrototyperData/Demo_03_Expression.nfo'
		   'PrototyperData/Demo_03_Expression.oz'
		   'PrototyperData/Demo_04_Canvas.nfo'
		   'PrototyperData/Demo_04_Canvas.oz'
		   'PrototyperData/Geometry_01.nfo'
		   'PrototyperData/Geometry_01.oz'
		   'PrototyperData/Geometry_02.nfo'
		   'PrototyperData/Geometry_02.oz'
		   'PrototyperData/Geometry_03.nfo'
		   'PrototyperData/Geometry_03.oz'
		   'PrototyperData/Geometry_04.nfo'
		   'PrototyperData/Geometry_04.oz'
		   'PrototyperData/Geometry_05.nfo'
		   'PrototyperData/Geometry_05.oz'
		   'PrototyperData/Geometry_06.nfo'
		   'PrototyperData/Geometry_06.oz'
		   'PrototyperData/Interaction_01.nfo'
		   'PrototyperData/Interaction_01.oz'
		   'PrototyperData/Interaction_02.nfo'
		   'PrototyperData/Interaction_02.oz'
		   'PrototyperData/Interaction_03.nfo'
		   'PrototyperData/Interaction_03.oz'
		   'PrototyperData/Interaction_04.nfo'
		   'PrototyperData/Interaction_04.oz'
		   'PrototyperData/Widget_button.nfo'
		   'PrototyperData/Widget_button.oz'
		   'PrototyperData/Widget_canvas.nfo'
		   'PrototyperData/Widget_canvas.oz'
		   'PrototyperData/Widget_checkbutton.nfo'
		   'PrototyperData/Widget_checkbutton.oz'
		   'PrototyperData/Widget_dropdownlistbox.nfo'
		   'PrototyperData/Widget_dropdownlistbox.oz'
		   'PrototyperData/Widget_entry.nfo'
		   'PrototyperData/Widget_entry.oz'
		   'PrototyperData/Widget_grid.nfo'
		   'PrototyperData/Widget_grid.oz'
		   'PrototyperData/Widget_label.nfo'
		   'PrototyperData/Widget_label.oz'
		   'PrototyperData/Widget_line.nfo'
		   'PrototyperData/Widget_line.oz'
		   'PrototyperData/Widget_listbox.nfo'
		   'PrototyperData/Widget_listbox.oz'
		   'PrototyperData/Widget_lr.nfo'
		   'PrototyperData/Widget_lr.oz'
		   'PrototyperData/Widget_menubutton.nfo'
		   'PrototyperData/Widget_menubutton.oz'
		   'PrototyperData/Widget_message.nfo'
		   'PrototyperData/Widget_message.oz'
		   'PrototyperData/Widget_numberentry.nfo'
		   'PrototyperData/Widget_numberentry.oz'
		   'PrototyperData/Widget_panel.nfo'
		   'PrototyperData/Widget_panel.oz'
		   'PrototyperData/Widget_placeholder.nfo'
		   'PrototyperData/Widget_placeholder.oz'
		   'PrototyperData/Widget_radiobutton.nfo'
		   'PrototyperData/Widget_radiobutton.oz'
		   'PrototyperData/Widget_rubberframe.nfo'
		   'PrototyperData/Widget_rubberframe.oz'
		   'PrototyperData/Widget_scale.nfo'
		   'PrototyperData/Widget_scale.oz'
		   'PrototyperData/Widget_scrollframe.nfo'
		   'PrototyperData/Widget_scrollframe.oz'
		   'PrototyperData/Widget_space.nfo'
		   'PrototyperData/Widget_space.oz'
		   'PrototyperData/Widget_td.nfo'
		   'PrototyperData/Widget_td.oz'
		   'PrototyperData/Widget_text.nfo'
		   'PrototyperData/Widget_text.oz'
		   'PrototyperData/Widget_toolbar.nfo'
		   'PrototyperData/Widget_toolbar.oz'
		   'PrototyperData/Widget_toplevel.nfo'
		   'PrototyperData/Widget_toplevel.oz'
		  ]
		)
   lib     : ['QTk.ozf' 'QTkDevel.ozf' 'QTkBare.ozf' 'Prototyper.ozf']
   %%src     : ['QTk.ozf' 'QTkDevel.ozf' 'QTkBare.ozf']
   rules   : o(
		'QTk.ozf' : ozl('QTkBare.ozf'))
   doc     : ['html/button.gif'
	      'html/bwoz1.gif'
	      'html/canvas.gif'
	      'html/checkbutton.gif'
	      'html/color.gif'
	      'html/dropdownlistbox.gif'
	      'html/entry.gif'
	      'html/grid.gif'
	      'html/index.html'
	      'html/label.gif'
	      'html/line.gif'
	      'html/listbox.gif'
	      'html/listcont.oz'
	      'html/load.gif'
	      'html/menubutton.gif'
	      'html/message.gif'
	      'html/node1.html'
	      'html/node10.html'
	      'html/node11.html'
	      'html/node12.html'
	      'html/node13.html'
	      'html/node14.html'
	      'html/node15.html'
	      'html/node16.html'
	      'html/node17.html'
	      'html/node18.html'
	      'html/node19.html'
	      'html/node2.html'
	      'html/node20.html'
	      'html/node21.html'
	      'html/node22.html'
	      'html/node23.html'
	      'html/node24.html'
	      'html/node25.html'
	      'html/node26.html'
	      'html/node27.html'
	      'html/node28.html'
	      'html/node29.html'
	      'html/node3.html'
	      'html/node30.html'
	      'html/node31.html'
	      'html/node32.html'
	      'html/node33.html'
	      'html/node34.html'
	      'html/node35.html'
	      'html/node36.html'
	      'html/node37.html'
	      'html/node38.html'
	      'html/node39.html'
	      'html/node4.html'
	      'html/node40.html'
	      'html/node41.html'
	      'html/node42.html'
	      'html/node43.html'
	      'html/node44.html'
	      'html/node45.html'
	      'html/node5.html'
	      'html/node6.html'
	      'html/node7.html'
	      'html/node8.html'
	      'html/node9.html'
	      'html/notepad.oz'
	      'html/numberentry.gif'
	      'html/ozdoc.css'
	      'html/page.gif'
	      'html/panel.gif'
	      'html/picture1.gif'
	      'html/picture10.gif'
	      'html/picture100.gif'
	      'html/picture11.gif'
	      'html/picture2.gif'
	      'html/picture3.gif'
	      'html/picture4.gif'
	      'html/picture5.gif'
	      'html/picture6.gif'
	      'html/picture8.gif'
	      'html/picture9.gif'
	      'html/placeholder.gif'
	      'html/printcanvas.gif'
	      'html/radiobutton.gif'
	      'html/rubberframe.gif'
	      'html/scale.gif'
	      'html/scrollbar.gif'
	      'html/scrollframe.gif'
	      'html/space.gif'
	      'html/tbbutton.gif'
	      'html/tbcheckbutton.gif'
	      'html/tbradiobutton.gif'
	      'html/tdlr.gif'
	      'html/text.gif'
	      'html/toplevel.gif'
	     ]
   )
