#!/bin/sh

glib_libs="-L/usr/local/bin -lgmodule-1.3 -lglib-1.3"
glib_cflags="-L/usr/local/bin -I/home/bruni/devel/wingtk/src/glib"
glib_thread_libs="-L/usr/local/bin -lgmodule -lgthread -lglib-1.3 -lpthread -ldl"
glib_thread_cflags="-I/home/bruni/devel/wingtk/src/glib -D_REENTRANT"

prefix=/usr/local/bin
exec_prefix=/usr/local/bin
exec_prefix_set=no

usage()
{
	cat <<EOF
Usage: gtk-config [OPTIONS] [LIBRARIES]
Options:
	[--prefix[=DIR]]
	[--exec-prefix[=DIR]]
	[--version]
	[--libs]
	[--cflags]
Libraries:
	gtk
	gthread
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

lib_gtk=yes

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo_prefix=yes
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo_exec_prefix=yes
      ;;
    --version)
      echo 1.3.0
      ;;
    --cflags)
      echo_cflags=yes
      ;;
    --libs)
      echo_libs=yes
      ;;
    gtk)
      lib_gtk=yes
      ;;
    gthread)
      lib_gthread=yes
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

if test "$echo_prefix" = "yes"; then
	echo $prefix
fi

if test "$echo_exec_prefix" = "yes"; then
	echo $exec_prefix
fi

if test "$lib_gthread" = "yes"; then
      glib_cflags="$glib_thread_cflags"
      glib_libs="$glib_thread_libs"
fi

if test "$echo_cflags" = "yes"; then
      echo -I/home/bruni/devel/wingtk/src/gtk+ -I/home/bruni/devel/wingtk/src/gtk+/gdk -I/home/bruni/devel/wingtk/imlib-1.9.10/gdk_imlib -I/home/bruni/devel/wingtk/src/glib
fi

if test "$echo_libs" = "yes"; then
      my_glib_libs=
      libdirs=-L/usr/local/bin
      for i in $glib_libs ; do
        if test $i != -L/usr/local/bin ; then
          if test -z "$my_glib_libs" ; then
            my_glib_libs="$i"
          else
            my_glib_libs="$my_glib_libs $i"
          fi
        fi
      done

      echo $libdirs -lgtk-1.3 -lgdk-1.3 $my_glib_libs
fi      

