#!/bin/sh
#
# Shamelessly ripped form gtk's gtk-config.in
#

gx_libs=" -limlib-jpeg -limlib-tiff -limlib-png -lz -lm"
gdk_gx_libs=" "
gdk_libs=""

prefix=/usr/local/bin
exec_prefix=/usr/local/bin
exec_prefix_set=no

usage="\
Usage: imlib-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--libs-gdk] [--cflags] [--cflags-gdk]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.9.8.1
      ;;
    --cflags)
      if test /usr/include != /usr/include ; then
        includes=-I/usr/include
      fi
      echo -I/home/bruni/devel/wingtk/src/imlib/gdk_imlib
      ;;
    --cflags-gdk)
      if test /usr/include != /usr/include ; then
        includes=-I/usr/include
      fi
      echo `gtk-config --cflags` $includes
      ;;
    --libs)
      libdirs=-L/usr/local/bin
      echo $libdirs $gx_libs
      ;;
    --libs-gdk)
      libdirs=-L/usr/local/bin
      echo $libdirs -lgdk_imlib$gdk_gx_libs `gtk-config --libs` $gdk_libs
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

exit 0
