# Generated automatically from Makefile.in by configure.
VPATH           = @srcdir@
SRCDIR          = @srcdir@

WHAT = constraints
MAIN = 0.sgml
SGMLSRCS = \
        fd_reference.sgml fset_tutorial.sgml            \
        ct_cpi_reference.sgml fd_tutorial.sgml          \
        lp_reference.sgml ct_cpi_tutorial.sgml          \
        fset_cpi_reference.sgml lp_tutorial.sgml        \
        fd_cpi_reference.sgml fset_cpi_tutorial.sgml    \
        fd_cpi_tutorial.sgml fset_reference.sgml        \
        lp_tutorial_intro.sgml fset_example.sgml        \
        mks_fd.oz mks_lp_a.oz mks_lp_b.oz mks_lp_c.oz   \
        mks_lp_d.oz mks_fdlp.oz mks_prob.oz simp_ex.oz  \
        fset_crew_problem.oz                            \
        fset_example_steiner.sgml                       \
        fset_example_hamming.sgml                       \
        fset_example_binpacking.sgml                    \
        fset_example_crew.sgml                          \
        fset_example_golf.sgml fset_steiner_order.oz    \
        fset_hamming.oz fset_steiner.oz fset_crew.oz    \
        fset_golf.oz fset_binpacking.oz                 \
        ri_class_ri.hh ri_class_riprofile.hh            \
        ri_class_riwakeup.hh ri_class_ridef.hh          \
        ri_class_rivar.hh ri_class_ri_lesseq.hh         \
        ri_class_riprop.hh ri_class_ri_expect.hh        \
        ri_class_rivirt-1.hh ri_class_rivirt-2.hh       \
        ri_class_rivirt-3.hh                            \
        constraints.bib
HTMLEXTRAFILES = \
        mks_fd_explorer.gif mks_fdlp_explorer.gif       \
        mks_lp_explorer.gif setdistr.gif                \
        fset_steiner_naive.gif fset_steiner_order.gif   \
        hamming_browser.gif golf_explorer.gif           \
        crew_browser.gif

OZDOCHTMLFLAGS =

include ../Makefile.common
