# -*-makefile-*-

VERSION		= 1.0
PKG_NAME	= duchier-ozpm-$(VERSION)
PKG_MOGUL_URI	= mogul:/duchier/ozpm
PKG_URI		= x-ozlib://duchier/tools/ozpm
PKG_INSTALLS	= FileUtils.ozf tester.exe Shell.ozf tester2.exe tester3.exe \
	zfile.so-$(PLATFORM) Archive.ozf tester5.exe ozpm.exe

all::
tester.exe:: tester.ozf FileUtils.ozf Shell.ozf
texter5.exe:: tester5.ozf Archive.ozf zfile.so-$(PLATFORM)
ozpm.exe:: ozpm.ozf
