# -*-makefile-*-

VERSION		= 1.0
PKG_NAME	= duchier-ozpm-$(VERSION)
PKG_MOGUL_URI	= mogul:/duchier/ozpm
PKG_URI		= x-ozlib://duchier/tools/ozpm
PKG_INSTALLS	= FileUtils.ozf tester.exe Shell.ozf

all::
tester.exe:: tester.ozf FileUtils.ozf Shell.ozf
