#!/bin/sh
#
# Author:
#   Leif Kornstaedt <kornstae@ps.uni-sb.de>
#
# Contributor:
#   Tobias Mueller <tmueller@ps.uni-sb.de>
#
# Copyright:
#   Leif Kornstaedt, 1998
#
# Last change:
#   $Date: 1998/07/30 23:09:31 $ by $Author: kornstae $
#   $Revision: 1.2 $
#
# This file is part of Mozart, an implementation of Oz 3:
#   $MOZARTURL$
#
# See the file "LICENSE" or
#   $LICENSEURL$
# for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL
# WARRANTIES.
#

if [ $# -ne 2 ]
then
    echo usage: `basename $0` \<input file\> \<output directory\> 1>&2
    exit 2
fi

infile=$1
outdir=$2

tmpdir=/tmp/ps2gif.$$
mkdir $tmpdir
cp $infile $tmpdir/x.tex

(cd $tmpdir

latex x 1>&2 || exit 1
dvips x.dvi -o x.ps 1>&2

(cat x.ps; echo quit) |
gs -q -dNOPAUSE \
-dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r102 \
-sDEVICE=ppmraw -sOutputFile=latex%d.ppm - 1>&2

for i in latex*.ppm; do
    o=`basename $i .ppm`.gif
    pnmcrop < $i | ppmtogif -interlace -transparent rgbi:1/1/1 > $o
    echo Wrote $o 1>&2
done)

mv $tmpdir/latex*.gif $outdir

rm -rf $tmpdir

exit 0
