# -*-makefile-*-

VERSION		= 1.0
PKG_NAME	= duchier-ozpm-$(VERSION)
PKG_MOGUL_URI	= mogul:/duchier/ozpm
PKG_URI		= x-ozlib://duchier/tools/ozpm
PKG_INSTALLS	= LS.ozf tester.exe

all::
tester.exe:: tester.ozf LS.ozf
