# -*-makefile-*-
# this file was provided by ozskel - read the ozskel documentation
# Here you may provide additional make rules for use in Makefile.in

OZMAKE_FILES = \
	Main.ozf Utils.ozf Path.ozf Shell.ozf Executor.ozf Attribs.ozf \
	Builder.ozf Makefiler.ozf Manager.ozf Installer.ozf Database.ozf \
	Cleaner.ozf Creator.ozf Extractor.ozf Lister.ozf Help.ozf \
	Uninstaller.ozf Errors.ozf Windows.ozf MakeGUI.ozf Fixes.ozf \
	DatabaseLib.ozf Config.ozf Mogul.ozf Pickler.ozf \
	ExecutorFast.ozf Depends.ozf

ozmake: ozmake.ozf
	$(OZL) $(OZLFLAGS) -x $< -o $@

ozmake.exe: ozmake.ozf
	$(OZL) $(OZLFLAGS) --target=windows -x $< -o $@

ozmake.ozf: $(OZMAKE_FILES)
	$(OZL) $(OZLFLAGS) Main.ozf -o $@

Help.ozf: Help.oz HELP.txt Utils.ozf
Utils.ozf: Utils.oz Path.ozf Windows.ozf Shell.ozf
Help.ozf: Utils.ozf HELP.txt

clean::
	-rm -f ozmake ozmake.exe

html: HELP.xml HELP.xsl Makefile.vars
	case `java -version 2>&1` in \
	Kaffe*) JAVACP=-addclasspath;; \
	*) JAVACP=-classpath;; \
	esac; \
	java $$JAVACP XT.jar com.jclark.xsl.sax.Driver HELP.xml HELP.xsl index.html OZMAKEOUTPUT=html OZMAKEVERSION=$(VERSION)

HELP.html: HELP.xml HELP.xsl Makefile.vars
	case `java -version 2>&1` in \
	Kaffe*) JAVACP=-addclasspath;; \
	*) JAVACP=-classpath;; \
	esac; \
	java $$JAVACP XT.jar com.jclark.xsl.sax.Driver HELP.xml HELP.xsl HELP.html OZMAKEOUTPUT=text OZMAKEVERSION=$(VERSION)
HELP.txt: HELP.html Makefile.vars
	lynx -dump $< > $@
txt: HELP.txt

doc: ozmake.xml ozmake.xsl
	case `java -version 2>&1` in \
	Kaffe*) JAVACP=-addclasspath;; \
	*) JAVACP=-classpath;; \
	esac; \
	java $$JAVACP XT.jar com.jclark.xsl.sax.Driver ozmake.xml ozmake.xsl ozmake.html

#publish: duchier-ozmake-$(VERSION).pkg
#duchier-ozmake-$(VERSION).pkg: $(OZMAKE_SOURCES) ./ozmake
#	./ozmake --publish -v -p duchier-ozmake-$(VERSION).pkg

duchier-ozmake.pkg: ozmake
	$(OZE) ./ozmake -cvp $@

install-prebuilt:: ozmake.ozf ozmake ozmake.exe duchier-ozmake.pkg
	$(INSTALL_FILE) ozmake.ozf $(PKGDIR)/ozmake.ozf
	$(INSTALL_FILE) ozmake $(PKGDIR)/ozmake
	$(INSTALL_FILE) ozmake.exe $(PKGDIR)/ozmake.exe
	$(INSTALL_FILE) ozmake.ozf $(PKGDIR)/ozmake-$(VERSION).ozf
	$(INSTALL_FILE) ozmake $(PKGDIR)/ozmake-$(VERSION)
	$(INSTALL_FILE) ozmake.exe $(PKGDIR)/ozmake-$(VERSION).exe
	$(INSTALL_FILE) duchier-ozmake.pkg $(PKGDIR)/duchier-ozmake.pkg
	$(INSTALL_FILE) duchier-ozmake.pkg $(PKGDIR)/duchier-ozmake-$(VERSION).pkg
