# -*-makefile-*-
# this file was provided by ozskel - read the ozskel documentation
# Here you may provide additional make rules for use in Makefile.in

OZMAKE_FILES = \
	Main.ozf Utils.ozf Path.ozf Shell.ozf Executor.ozf Attribs.ozf \
	Builder.ozf Makefile.ozf Manager.ozf Installer.ozf Database.ozf \
	Cleaner.ozf Creator.ozf Extractor.ozf Lister.ozf Help.ozf \
	Uninstaller.ozf

ozmake: ozmake.ozf
	$(OZL) $(OZLFLAGS) -x $< -o $@

ozmake.ozf: $(OZMAKE_FILES)
	$(OZL) $(OZLFLAGS) Main.ozf -o $@

Help.ozf: Help.oz HELP.txt Utils.ozf

clean::
	-rm -f ozmake

index.html: HELP.xml HELP.xsl
	java -cp XT.jar com.jclark.xsl.sax.Driver HELP.xml HELP.xsl index.html

install-prebuilt:
	$(INSTALL_FILE) ozmake.ozf $(PKGDIR)/ozmake.ozf
	$(INSTALL_FILE) ozmake $(PKGDIR)/ozmake
	$(INSTALL_FILE) ozmake.exe $(PKGDIR)/ozmake.exe
