(ozdoc-fontify-alist "OZ" '((N39 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N49 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N63 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N71 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N75 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N79 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N88 . "HttpReqRep")
))
(ozdoc-fontify-alist "OZ" '((N94 . "HttpHeader")
))
(ozdoc-fontify-alist "OZ" '((N100 . "ListUtils")
))
(ozdoc-fontify-alist "OZ" '((N106 . "OpenConnection")
))
(ozdoc-fontify-alist "OZ" '((N114 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N122 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N128 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N132 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N137 . "Service")
))
(ozdoc-fontify-alist "OZ" '((N141 . "CgiGET")
))
(ozdoc-fontify-alist "OZ" '((N145 . "CgiPOST")
))
(ozdoc-fontify-alist "OZ" '((N149 . "CgiISINDEX")
))
(ozdoc-fontify-alist "OZ" '((N153 . "UrlGET")
))
(ozdoc-fontify-alist "OZ" '((N157 . "UrlHEAD")
))
(ozdoc-fontify-alist "OZ" '((N161 . "Service")
))
(ozdoc-fontify-alist "OZ" '((N172 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N188 . "conPremClosed")
))
(ozdoc-fontify-alist "OZ" '((N194 . "errCloseCon")
))
(ozdoc-fontify-alist "OZ" '((N200 . "errCloseFile")
))
(ozdoc-fontify-alist "OZ" '((N206 . "errReadSocket")
))
(ozdoc-fontify-alist "OZ" '((N212 . "errRemFile")
))
(ozdoc-fontify-alist "OZ" '((N218 . "errOpenCon")
))
(ozdoc-fontify-alist "OZ" '((N224 . "errOpenFile")
))
(ozdoc-fontify-alist "OZ" '((N230 . "errWriteFile")
))
(ozdoc-fontify-alist "OZ" '((N236 . "errWriteSocket")
))
(ozdoc-fontify-alist "OZ" '((N256 . "errCgiPrms")
))
(ozdoc-fontify-alist "OZ" '((N262 . "errLargeCgiPrms")
))
(ozdoc-fontify-alist "OZ" '((N268 . "errUrlChrs")
))
(ozdoc-fontify-alist "OZ" '((N293 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N298 . "inPrms(file: ")
(N302 . "FileName")
(N303 . " <= given Url based
       rTime: ")
(N307 . "RTime")
(N308 . " <= 25
       smpl: ")
(N312 . "Smpl")
(N313 . " <= 45
       toFile: ")
(N317 . "ToFile")
(N318 . " <= true
       toStrm: ")
(N322 . "ToStrm")
(N323 . " <= false)")
))
(ozdoc-fontify-alist "OZ" '((N329 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N334 . "FileName")
))
(ozdoc-fontify-alist "OZ" '((N339 . "RTime")
))
(ozdoc-fontify-alist "OZ" '((N344 . "Smpl")
))
(ozdoc-fontify-alist "OZ" '((N348 . "fetchRate")
))
(ozdoc-fontify-alist "OZ" '((N356 . "ToFile")
))
(ozdoc-fontify-alist "OZ" '((N361 . "ToStrm")
))
(ozdoc-fontify-alist "OZ" '((N366 . "Url")
))
(ozdoc-fontify-alist "OZ" '((N374 . "\"http://www.info.ucl.ac.be\"")
))
(ozdoc-fontify-alist "OZ" '((N378 . "\"www.yahoo.com\"")
))
(ozdoc-fontify-alist "OZ" '((N392 . "HttpPrms")
))
(ozdoc-fontify-alist "OZ" '((N397 . "httpPrms(server: ")
(N401 . "Server")
(N402 . " 
         date: ")
(N406 . "Date")
(N407 . " 
         last_modified: ")
(N411 . "Last_Modified")
(N412 . " 
         location: ")
(N416 . "Location")
(N417 . " 
         content_length: ")
(N421 . "Content_Length")
(N422 . "
         content_type: ")
(N426 . "Content_Type")
(N427 . "
         content_encoding: ")
(N431 . "Content_Encoding")
(N432 . ") ")
))
(ozdoc-fontify-alist "OZ" '((N437 . "HttpPrms")
))
(ozdoc-fontify-alist "OZ" '((N442 . "Server")
))
(ozdoc-fontify-alist "OZ" '((N447 . "Date")
))
(ozdoc-fontify-alist "OZ" '((N456 . "Last_Modified")
))
(ozdoc-fontify-alist "OZ" '((N465 . "Location")
))
(ozdoc-fontify-alist "OZ" '((N474 . "Content_Length")
))
(ozdoc-fontify-alist "OZ" '((N479 . "Content_Type")
))
(ozdoc-fontify-alist "OZ" '((N484 . "Content_Encoding")
))
(ozdoc-fontify-alist "OZ" '((N490 . "OutPrms")
))
(ozdoc-fontify-alist "OZ" '((N495 . "outPrms(file: ")
(N499 . "FileName")
(N500 . " 
        toFile: ")
(N504 . "ToFile")
(N505 . " 
        toStrm: ")
(N509 . "ToStrm")
(N510 . " 
        sOut: ")
(N514 . "SOut")
(N515 . " 
        time: ")
(N519 . "Time")
(N520 . "
        status: ")
(N524 . "Status")
(N525 . "
        sizeRead: ")
(N529 . "SizeRead")
(N530 . ") ")
))
(ozdoc-fontify-alist "OZ" '((N536 . "OutPrms")
))
(ozdoc-fontify-alist "OZ" '((N540 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N548 . "SOut")
))
(ozdoc-fontify-alist "OZ" '((N552 . "toStrm")
))
(ozdoc-fontify-alist "OZ" '((N556 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N560 . "false")
))
(ozdoc-fontify-alist "OZ" '((N572 . "SOut")
))
(ozdoc-fontify-alist "OZ" '((N577 . "Time")
))
(ozdoc-fontify-alist "OZ" '((N582 . "Status")
))
(ozdoc-fontify-alist "OZ" '((N586 . "\"200\"")
))
(ozdoc-fontify-alist "OZ" '((N594 . "\"301\"")
))
(ozdoc-fontify-alist "OZ" '((N603 . "SizeRead")
))
(ozdoc-fontify-alist "OZ" '((N611 . "HttpClient.service")
))
(ozdoc-fontify-alist "OZ" '((N616 . "Service")
))
(ozdoc-fontify-alist "OZ" '((N624 . "bytesRead")
))
(ozdoc-fontify-alist "OZ" '((N629 . "bytesRead(")
(N633 . "N")
(N634 . ")")
))
(ozdoc-fontify-alist "OZ" '((N640 . "N")
))
(ozdoc-fontify-alist "OZ" '((N646 . "closeAll")
))
(ozdoc-fontify-alist "OZ" '((N651 . "closeAll(")
(N655 . "Trace")
(N656 . ")")
))
(ozdoc-fontify-alist "OZ" '((N664 . "Trace")
))
(ozdoc-fontify-alist "OZ" '((N668 . "false")
))
(ozdoc-fontify-alist "OZ" '((N672 . "Trace")
))
(ozdoc-fontify-alist "OZ" '((N676 . "true")
))
(ozdoc-fontify-alist "OZ" '((N680 . "errCloseCon")
))
(ozdoc-fontify-alist "OZ" '((N684 . "errCloseFile")
))
(ozdoc-fontify-alist "OZ" '((N688 . "errRemFile")
))
(ozdoc-fontify-alist "OZ" '((N697 . "fetchRate")
))
(ozdoc-fontify-alist "OZ" '((N702 . "fetchRate(")
(N706 . "Rate")
(N707 . ")")
))
(ozdoc-fontify-alist "OZ" '((N713 . "Rate")
))
(ozdoc-fontify-alist "OZ" '((N717 . "Smpl")
))
(ozdoc-fontify-alist "OZ" '((N726 . "init")
))
(ozdoc-fontify-alist "OZ" '((N731 . "init")
))
(ozdoc-fontify-alist "OZ" '((N739 . "service")
))
(ozdoc-fontify-alist "OZ" '((N744 . "service(")
(N748 . "Meth")
(N749 . " ")
(N753 . "Url")
(N754 . " ")
(N758 . "InPrms")
(N759 . " ")
(N763 . "Pairs")
(N764 . " ")
(N768 . "OutPrms")
(N769 . " ")
(N773 . "HttpPrms")
(N774 . ")")
))
(ozdoc-fontify-alist "OZ" '((N780 . "Meth")
))
(ozdoc-fontify-alist "OZ" '((N784 . "Url")
))
(ozdoc-fontify-alist "OZ" '((N788 . "Meth")
))
(ozdoc-fontify-alist "OZ" '((N792 . "\"GET\"")
))
(ozdoc-fontify-alist "OZ" '((N796 . "\"POST\"")
))
(ozdoc-fontify-alist "OZ" '((N812 . "Pairs")
))
(ozdoc-fontify-alist "OZ" '((N816 . "\"name=value\"")
))
(ozdoc-fontify-alist "OZ" '((N828 . "\"value\"")
))
(ozdoc-fontify-alist "OZ" '((N838 . "OutPrms")
))
(ozdoc-fontify-alist "OZ" '((N842 . "HttpPrms")
))
(ozdoc-fontify-alist "OZ" '((N849 . "errRemFile")
))
(ozdoc-fontify-alist "OZ" '((N860 . "startTemp")
))
(ozdoc-fontify-alist "OZ" '((N865 . "startTemp")
))
(ozdoc-fontify-alist "OZ" '((N871 . "stopTemp")
))
(ozdoc-fontify-alist "OZ" '((N877 . "stopTemp")
))
(ozdoc-fontify-alist "OZ" '((N882 . "stopTemp")
))
(ozdoc-fontify-alist "OZ" '((N888 . "startTemp")
))
(ozdoc-fontify-alist "OZ" '((N895 . "HttpClient.cgiGET")
))
(ozdoc-fontify-alist "OZ" '((N900 . "HttpClient.cgiGET")
))
(ozdoc-fontify-alist "OZ" '((N904 . "HttpClient.service")
))
(ozdoc-fontify-alist "OZ" '((N913 . "HttpClient.cgiGET")
))
(ozdoc-fontify-alist "OZ" '((N925 . "init")
))
(ozdoc-fontify-alist "OZ" '((N930 . "init(")
(N934 . "InPrms")
(N935 . ")")
))
(ozdoc-fontify-alist "OZ" '((N941 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N947 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N956 . "getService")
))
(ozdoc-fontify-alist "OZ" '((N961 . "getService(")
(N965 . "Url")
(N966 . " ")
(N970 . "CgiPairs")
(N971 . " ")
(N975 . "OutPrms")
(N976 . " ")
(N980 . "HttpPrms")
(N981 . ")")
))
(ozdoc-fontify-alist "OZ" '((N987 . "CgiPairs")
))
(ozdoc-fontify-alist "OZ" '((N995 . "Url")
))
(ozdoc-fontify-alist "OZ" '((N999 . "CgiPairs")
))
(ozdoc-fontify-alist "OZ" '((N1003 . "\"name=value\"")
))
(ozdoc-fontify-alist "OZ" '((N1007 . "[\"Age=35\" \"Occupation=research assistant\"]")
))
(ozdoc-fontify-alist "OZ" '((N1013 . "OutPrms")
))
(ozdoc-fontify-alist "OZ" '((N1017 . "HttpPrms")
))
(ozdoc-fontify-alist "OZ" '((N1024 . "errRemFile")
))
(ozdoc-fontify-alist "OZ" '((N1036 . "HttpClient.cgiPOST")
))
(ozdoc-fontify-alist "OZ" '((N1041 . "HttpClient.cgiPOST")
))
(ozdoc-fontify-alist "OZ" '((N1045 . "HttpClient.service")
))
(ozdoc-fontify-alist "OZ" '((N1054 . "HttpClient.cgiPOST")
))
(ozdoc-fontify-alist "OZ" '((N1066 . "init")
))
(ozdoc-fontify-alist "OZ" '((N1071 . "init(")
(N1075 . "InPrms")
(N1076 . ")")
))
(ozdoc-fontify-alist "OZ" '((N1082 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N1088 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N1097 . "getService")
))
(ozdoc-fontify-alist "OZ" '((N1102 . "getService(")
(N1106 . "Url")
(N1107 . " ")
(N1111 . "CgiPairs")
(N1112 . " ")
(N1116 . "OutPrms")
(N1117 . " ")
(N1121 . "HttpPrms")
(N1122 . ")")
))
(ozdoc-fontify-alist "OZ" '((N1128 . "CgiPairs")
))
(ozdoc-fontify-alist "OZ" '((N1136 . "Url")
))
(ozdoc-fontify-alist "OZ" '((N1140 . "CgiPairs")
))
(ozdoc-fontify-alist "OZ" '((N1144 . "\"name=value\"")
))
(ozdoc-fontify-alist "OZ" '((N1150 . "OutPrms")
))
(ozdoc-fontify-alist "OZ" '((N1154 . "HttpPrms")
))
(ozdoc-fontify-alist "OZ" '((N1161 . "errRemFile")
))
(ozdoc-fontify-alist "OZ" '((N1173 . "HttpClient.cgiISINDEX")
))
(ozdoc-fontify-alist "OZ" '((N1178 . "HttpClient.cgiISINDEX")
))
(ozdoc-fontify-alist "OZ" '((N1182 . "HttpClient.service")
))
(ozdoc-fontify-alist "OZ" '((N1191 . "HttpClient.cgiISINDEX")
))
(ozdoc-fontify-alist "OZ" '((N1203 . "init")
))
(ozdoc-fontify-alist "OZ" '((N1208 . "init(")
(N1212 . "InPrms")
(N1213 . ")")
))
(ozdoc-fontify-alist "OZ" '((N1219 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N1225 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N1234 . "getService")
))
(ozdoc-fontify-alist "OZ" '((N1239 . "getService(")
(N1243 . "Url")
(N1244 . " ")
(N1248 . "IndexPairs")
(N1249 . " ")
(N1253 . "OutPrms")
(N1254 . " ")
(N1258 . "HttpPrms")
(N1259 . ")")
))
(ozdoc-fontify-alist "OZ" '((N1265 . "IndexPairs")
))
(ozdoc-fontify-alist "OZ" '((N1273 . "Url")
))
(ozdoc-fontify-alist "OZ" '((N1277 . "IndexPairs")
))
(ozdoc-fontify-alist "OZ" '((N1281 . "\"value\"")
))
(ozdoc-fontify-alist "OZ" '((N1285 . "\"research assistant\"")
))
(ozdoc-fontify-alist "OZ" '((N1291 . "OutPrms")
))
(ozdoc-fontify-alist "OZ" '((N1295 . "HttpPrms")
))
(ozdoc-fontify-alist "OZ" '((N1302 . "errRemFile")
))
(ozdoc-fontify-alist "OZ" '((N1314 . "HttpClient.urlGET")
))
(ozdoc-fontify-alist "OZ" '((N1319 . "HttpClient.urlGET")
))
(ozdoc-fontify-alist "OZ" '((N1323 . "HttpClient.service")
))
(ozdoc-fontify-alist "OZ" '((N1332 . "HttpClient.urlGET")
))
(ozdoc-fontify-alist "OZ" '((N1344 . "init")
))
(ozdoc-fontify-alist "OZ" '((N1349 . "init(")
(N1353 . "InPrms")
(N1354 . ")")
))
(ozdoc-fontify-alist "OZ" '((N1360 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N1366 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N1375 . "getService")
))
(ozdoc-fontify-alist "OZ" '((N1380 . "getService(")
(N1384 . "Url")
(N1385 . " ")
(N1389 . "OutPrms")
(N1390 . " ")
(N1394 . "HttpPrms")
(N1395 . ")")
))
(ozdoc-fontify-alist "OZ" '((N1401 . "Url")
))
(ozdoc-fontify-alist "OZ" '((N1407 . "OutPrms")
))
(ozdoc-fontify-alist "OZ" '((N1411 . "HttpPrms")
))
(ozdoc-fontify-alist "OZ" '((N1418 . "errRemFile")
))
(ozdoc-fontify-alist "OZ" '((N1430 . "HttpClient.urlHEAD")
))
(ozdoc-fontify-alist "OZ" '((N1435 . "HttpClient.urlHEAD")
))
(ozdoc-fontify-alist "OZ" '((N1439 . "HttpClient.service")
))
(ozdoc-fontify-alist "OZ" '((N1448 . "HttpClient.urlHEAD")
))
(ozdoc-fontify-alist "OZ" '((N1460 . "init")
))
(ozdoc-fontify-alist "OZ" '((N1465 . "init(")
(N1469 . "InPrms")
(N1470 . ")")
))
(ozdoc-fontify-alist "OZ" '((N1476 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N1482 . "InPrms")
))
(ozdoc-fontify-alist "OZ" '((N1491 . "getService")
))
(ozdoc-fontify-alist "OZ" '((N1496 . "getService(")
(N1500 . "Url")
(N1501 . " ")
(N1505 . "OutPrms")
(N1506 . " ")
(N1510 . "HttpPrms")
(N1511 . ")")
))
(ozdoc-fontify-alist "OZ" '((N1517 . "Url")
))
(ozdoc-fontify-alist "OZ" '((N1523 . "OutPrms")
))
(ozdoc-fontify-alist "OZ" '((N1527 . "sOut")
))
(ozdoc-fontify-alist "OZ" '((N1531 . "HttpPrms")
))
(ozdoc-fontify-alist "OZ" '((N1538 . "errRemFile")
))
(ozdoc-fontify-alist "OZ" '((N1557 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N1561 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N1565 . "CgiGET")
))
(ozdoc-fontify-alist "OZ" '((N1569 . "CgiPOST")
))
(ozdoc-fontify-alist "OZ" '((N1573 . "CgiISINDEX")
))
(ozdoc-fontify-alist "OZ" '((N1577 . "UrlGET")
))
(ozdoc-fontify-alist "OZ" '((N1581 . "UrlHEAD")
))
(ozdoc-fontify-alist "OZ" '((N1585 . "import")
))
(ozdoc-fontify-alist "OZ" '((N1589 . "'HttpClient.ozf'")
))
(ozdoc-fontify-alist "OZ" '((N1599 . "Url")
))
(ozdoc-fontify-alist "OZ" '((N1603 . "HttpClient.getUrl")
))
(ozdoc-fontify-alist "OZ" '((N1607 . "init")
))
(ozdoc-fontify-alist "OZ" '((N1611 . "getService")
))
(ozdoc-fontify-alist "OZ" '((N1617 . "Url")
))
(ozdoc-fontify-alist "OZ" '((N1621 . "\"index.html\"")
))
(ozdoc-fontify-file "OZ" 'N1629 "exmpl1.oz")
(ozdoc-fontify-alist "OZ" '((N1636 . "HttpClient.getHEAD")
))
(ozdoc-fontify-alist "OZ" '((N1646 . "HttpClient.cgiGET")
))
(ozdoc-fontify-alist "OZ" '((N1650 . "CgiParams")
))
(ozdoc-fontify-alist "OZ" '((N1654 . "\"name=value\"")
))
(ozdoc-fontify-alist "OZ" '((N1658 . "\"travel\"")
))
(ozdoc-fontify-alist "OZ" '((N1664 . "OutPrms.sizeRead")
))
(ozdoc-fontify-alist "OZ" '((N1668 . "HttpPrms.server")
))
(ozdoc-fontify-file "OZ" 'N1676 "exmpl2.oz")
(ozdoc-fontify-alist "OZ" '((N1684 . "HttpClient.cgiPOST")
))
(ozdoc-fontify-alist "OZ" '((N1688 . "HttpClient.cgiISINDEX")
))
(ozdoc-fontify-alist "OZ" '((N1692 . "CgiParams")
))
(ozdoc-fontify-alist "OZ" '((N1702 . "fetchRate")
))
(ozdoc-fontify-alist "OZ" '((N1706 . "bytesRead")
))
(ozdoc-fontify-alist "OZ" '((N1710 . "stopTemp")
))
(ozdoc-fontify-alist "OZ" '((N1714 . "startTemp")
))
(ozdoc-fontify-alist "OZ" '((N1718 . "GetRate")
))
(ozdoc-fontify-alist "OZ" '((N1726 . "toStrm")
))
(ozdoc-fontify-alist "OZ" '((N1730 . "true")
))
(ozdoc-fontify-alist "OZ" '((N1734 . "toFile")
))
(ozdoc-fontify-alist "OZ" '((N1738 . "true")
))
(ozdoc-fontify-alist "OZ" '((N1742 . "\"temp\"")
))
(ozdoc-fontify-alist "OZ" '((N1746 . "ProcessStrm")
))
(ozdoc-fontify-file "OZ" 'N1754 "exmpl3.oz")
(ozdoc-fontify-alist "OZ" '((N1766 . "Url1")
))
(ozdoc-fontify-alist "OZ" '((N1770 . "Url2")
))
(ozdoc-fontify-file "OZ" 'N1778 "exmpl4.oz")
(ozdoc-fontify-alist "OZ" '((N1794 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N1804 . "HttpClient")
))
(ozdoc-fontify-alist "OZ" '((N1808 . "Services")
))
(ozdoc-fontify-alist "OZ" '((N1812 . "Options")
))
(ozdoc-fontify-alist "OZ" '((N1821 . "text")
))
(ozdoc-fontify-alist "OZ" '((N1849 . "bwoz.oz")
))
(ozdoc-fontify-alist "OZ" '((N1853 . "ozc -x bwoz.oz")
))
(ozdoc-fontify-alist "OZ" '((N1858 . "bwoz")
))
(ozdoc-fontify-alist "OZ" '((N1873 . "HttpClient")
))
