# Generated automatically from Makefile.in by configure.
SRCTOP          = /pirates/tools/Oz/mozart-source/mozart
SRCDIR          = /usr/staff/ned/oz/QTkDoc/http
VPATH           = /usr/staff/ned/oz/QTkDoc/http


WHAT    = http
MAIN    = http.sgml
WHATCLASS=wp
PRINTNAME=WindowProgramming
SGMLSRCS =1_introduction.sgml             55_widgetnumberentry.sgml\
2_example.sgml                  56_widgetpanel.sgml\
3_basics.sgml                   57_widgetplaceholder.sgml\
41_widgetbutton.sgml            58_widgetradiobutton.sgml\
42_widgetcanvas.sgml            59_widgetscrollframe.sgml\
43_widgetcheckbutton.sgml       5_misc.sgml\
44_widgetdropdownlistbox.sgml   60_widgettbbutton.sgml\
45_widgetentry.sgml             61_widgettbcheckbutton.sgml\
46_widgetlabel.sgml             62_widgettbradiobutton.sgml\
47_widgetlistbox.sgml           63_widgettext.sgml\
48_widgetline.sgml              64_widgettdlr.sgml\
49_widgetrubberframe.sgml       book.sgml\
4_widgets.sgml                  defaultwidget.sgml\
50_widgetscale.sgml             http.sgml\
51_widgetscrollbar.sgml         param_activebackground.sgml\
52_widgetspace.sgml             param_init_text.sgml\
53_widgetmenubutton.sgml        test.sgml\
54_widgetmessage.sgml           Widget_button.sgml\
65_widgettoplevel.sgml


include Makefile.common
