# -*-makefile-*-
# this file was provided by ozskel - read the ozskel documentation
# Here you may provide additional make rules for use in Makefile.in

OZMAKE_FILES = \
	Main.ozf Utils.ozf Path.ozf Shell.ozf Executor.ozf Attribs.ozf \
	Builder.ozf Makefiler.ozf Manager.ozf Installer.ozf Database.ozf \
	Cleaner.ozf Creator.ozf Extractor.ozf Lister.ozf Help.ozf \
	Uninstaller.ozf Errors.ozf Windows.ozf MakeGUI.ozf Fixes.ozf \
	DatabaseLib.ozf Config.ozf Mogul.ozf Pickler.ozf \
	ExecutorFast.ozf Depends.ozf

ozmake: ozmake.ozf
	$(OZL) $(OZLFLAGS) -x $< -o $@

ozmake.exe: ozmake.ozf
	$(OZL) $(OZLFLAGS) --target=windows -x $< -o $@

ozmake.ozf: $(OZMAKE_FILES)
	$(OZL) $(OZLFLAGS) Main.ozf -o $@

Help.ozf: Help.oz HELP.txt Utils.ozf
Utils.ozf: Utils.oz Path.ozf Windows.ozf Shell.ozf
Help.ozf: Utils.ozf HELP.txt

clean::
	-rm -f ozmake ozmake.exe

have.xsltproc:
	@if xsltproc -V 1>/dev/null 2>&1; then \
	    : ; \
	else \
	    echo >&2 "xsltproc not found, but necessary to build the (html) documentation"; \
	    echo >&2 "(see http://xmlsoft.org/XSLT/xsltproc2.html)"; \
	    exit -1; \
	fi

have.lynx:
	@if lynx -version 1>/dev/null 2>&1; then \
	    : ; \
	else \
	    echo >&2 "lynx not found, but necessary to build the (text) documentation"; \
	    echo >&2 "(see http://lynx.browser.org/)"; \
	fi

html: have.xsltproc HELP.xml HELP.xsl Makefile.vars
	xsltproc -o index.html \
		--stringparam OZMAKEOUTPUT html \
		--stringparam OZMAKEVERSION $(VERSION) \
		HELP.xsl HELP.xml

HELP.html: have.xsltproc HELP.xml HELP.xsl Makefile.vars
	xsltproc -o HELP.html \
		--stringparam OZMAKEOUTPUT text \
		--stringparam OZMAKEVERSION $(VERSION) \
		HELP.xsl HELP.xml

HELP.txt: have.lynx HELP.html Makefile.vars
	lynx -dump HELP.html > HELP.txt

txt: HELP.txt

doc: have.xsltproc ozmake.xml ozmake.xsl
	xsltproc -o ozmake.html \
		ozmake.xsl ozmake.xml

#publish: duchier-ozmake-$(VERSION).pkg
#duchier-ozmake-$(VERSION).pkg: $(OZMAKE_SOURCES) ./ozmake
#	./ozmake --publish -v -p duchier-ozmake-$(VERSION).pkg

duchier-ozmake.pkg: ozmake
	$(OZE) ./ozmake -cvp $@

install-prebuilt:: ozmake.ozf ozmake ozmake.exe duchier-ozmake.pkg
	$(INSTALL_FILE) ozmake.ozf $(PKGDIR)/ozmake.ozf
	$(INSTALL_FILE) ozmake $(PKGDIR)/ozmake
	$(INSTALL_FILE) ozmake.exe $(PKGDIR)/ozmake.exe
	$(INSTALL_FILE) ozmake.ozf $(PKGDIR)/ozmake-$(VERSION).ozf
	$(INSTALL_FILE) ozmake $(PKGDIR)/ozmake-$(VERSION)
	$(INSTALL_FILE) ozmake.exe $(PKGDIR)/ozmake-$(VERSION).exe
	$(INSTALL_FILE) duchier-ozmake.pkg $(PKGDIR)/duchier-ozmake.pkg
	$(INSTALL_FILE) duchier-ozmake.pkg $(PKGDIR)/duchier-ozmake-$(VERSION).pkg
