# -*-makefile-*-
# this file was provided by ozskel - read the ozskel documentation
# Here you may provide additional make rules for use in Makefile.in

OZMAKE_FILES = \
	Main.ozf Utils.ozf Path.ozf Shell.ozf Executor.ozf Attribs.ozf \
	Builder.ozf Makefile.ozf Manager.ozf Installer.ozf Database.ozf \
	Cleaner.ozf Creator.ozf Extractor.ozf Lister.ozf Help.ozf \
	Uninstaller.ozf Errors.ozf Windows.ozf MakeGUI.ozf Fixes.ozf

ozmake: ozmake.ozf
	$(OZL) $(OZLFLAGS) -x $< -o $@

ozmake.exe: ozmake.ozf
	$(OZL) $(OZLFLAGS) --target=windows -x $< -o $@

ozmake.ozf: $(OZMAKE_FILES)
	$(OZL) $(OZLFLAGS) Main.ozf -o $@

Help.ozf: Help.oz HELP.txt Utils.ozf
Utils.ozf: Utils.oz Path.ozf Windows.ozf Shell.ozf
Help.ozf: Utils.ozf HELP.txt

clean::
	-rm -f ozmake

html: HELP.xml HELP.xsl Makefile.vars
	case `java -version 2>&1` in \
	Kaffe*) JAVACP=-addclasspath;; \
	*) JAVACP=-classpath;; \
	esac; \
	java $$JAVACP XT.jar com.jclark.xsl.sax.Driver HELP.xml HELP.xsl index.html OZMAKEOUTPUT=html OZMAKEVERSION=$(VERSION)

HELP.html: HELP.xml HELP.xsl Makefile.vars
	case `java -version 2>&1` in \
	Kaffe*) JAVACP=-addclasspath;; \
	*) JAVACP=-classpath;; \
	esac; \
	java $$JAVACP XT.jar com.jclark.xsl.sax.Driver HELP.xml HELP.xsl HELP.html OZMAKEOUTPUT=text OZMAKEVERSION=$(VERSION)
HELP.txt: HELP.html Makefile.vars
	lynx -dump $< > $@
txt: HELP.txt

install-prebuilt:
	$(INSTALL_FILE) ozmake.ozf $(PKGDIR)/ozmake.ozf
	$(INSTALL_FILE) ozmake $(PKGDIR)/ozmake
	$(INSTALL_FILE) ozmake.exe $(PKGDIR)/ozmake.exe
	$(INSTALL_FILE) ozmake.ozf $(PKGDIR)/ozmake-$(VERSION).ozf
	$(INSTALL_FILE) ozmake $(PKGDIR)/ozmake-$(VERSION)
	$(INSTALL_FILE) ozmake.exe $(PKGDIR)/ozmake-$(VERSION).exe
