# -*-makefile-*-
# this file was provided by ozskel - read the ozskel documentation
# Here you may provide additional make rules for use in Makefile.in

ozmake: Main.ozf Utils.ozf Path.ozf Shell.ozf Executor.ozf Attribs.ozf \
	Builder.ozf Makefile.ozf Manager.ozf Installer.ozf Database.ozf \
	Cleaner.ozf Creator.ozf Extractor.ozf Lister.ozf Help.ozf \
	Uninstaller.ozf
	$(OZL) $(OZLFLAGS) -x Main.ozf -o $@

Help.ozf: Help.oz HELP.txt Utils.ozf

clean::
	-rm -f ozmake
