# -*-makefile-*-
# this file was provided by ozskel - read the ozskel documentation
# Here you set variables used by Makefile.in

#VERSION		=
#PKG_NAME	= lewinsky-disaster-$(VERSION)
#PKG_MOGUL_URI	= mogul:/clinton/lewinsky
#PKG_URI		= x-ozlib://clinton/monica
#PKG_SOURCES	=
PKG_INSTALLS_BIN= ozmake
#PKG_UPDATE	= tgz tarz
#PKG_INSTALLS_DOC=

