WINDIR=Y:/.root/project/ps/soft/win32-i486

# at SICS use
#WINDIR=Y:/.root/home/scheidhr/build/packages/win32-i486

# code with debugging infos
COPT = -Zi -W3

# for fast code
#COPT = -Ox


tk.exe: winMain.obj
	cl $(COPT) -MT -nologo -Fetk.exe winMain.obj \
	   $(WINDIR)/lib/tcl80.lib $(WINDIR)/lib/tk80.lib user32.lib

winMain.obj: winMain.cc
	cl $(COPT) -nologo -MT -c -Tp winMain.cc -I$(WINDIR)/include
