# $Id$
# Benjamin Lorenz <lorenz@ps.uni-sb.de>

install:
	install -m 444 pre.oz config.oz emacs.oz thr.oz \
	manager.oz ozcar.oz frontend.oz main.oz exit.oz \
	dialog.oz tkext.oz \
	/project/ps/soft/oz-devel/oz/tools/ozcar
