# $Id$
# Benjamin Lorenz <lorenz@ps.uni-sb.de>

install:
	install -m 444 \
            ozcar-prelude.oz \
            string.oz        \
            tk.oz            \
            config.oz        \
                             \
            tree.oz          \
            thread.oz        \
                             \
            source.oz        \
                             \
            menu.oz          \
            dialog.oz        \
            gui.oz           \
                             \
            ozcar.oz         \
            main.oz          \
	/project/ps/soft/oz-devel/oz/tools/ozcar-devel
