http-html/index.html:1_introduction.sgml             53_widgetmenubutton.sgml \
1bis_prototyper.sgml            54_widgetmessage.sgml \
2_example.sgml                  55_widgetnumberentry.sgml \
3_basics.sgml                   56_widgetpanel.sgml \
41_widgetbutton.sgml            57_widgetplaceholder.sgml \
42_widgetcanvas.sgml            58_widgetradiobutton.sgml \
43_widgetcheckbutton.sgml       59_widgetscrollframe.sgml \
44_widgetdropdownlistbox.sgml   5_misc.sgml \
45_widgetentry.sgml             60_widgettbbutton.sgml \
46_widgetlabel.sgml             61_widgettbcheckbutton.sgml \
47_widgetlistbox.sgml           62_widgettbradiobutton.sgml \
48_widgetline.sgml              63_widgettext.sgml \
49_widgetrubberframe.sgml       64_widgettdlr.sgml \
4_widgets.sgml                  65_widgettoplevel.sgml \
50_widgetscale.sgml             book.sgml \
51_widgetscrollbar.sgml         htmlsplit.sgml \
52_widgetspace.sgml             http.sgml
	ozdoc   --in=http.sgml --out=http-html \
--type=html-stylesheets --stylesheet=ozdoc.css \
--link=Top,../index.html \
--bib-path=/pirates/staff/ned/oz/QTkDoc:/pirates/tools/Oz/mozart-source/mozart_backup/doc \
--bst-path=/pirates/tools/Oz/mozart-source/mozart_backup/doc/utilities \
--latexdb=latex.db --ozdoc-home=. \
--xrefdb=../xref.db --xrefdir=http --indexdb=../index.db \
--make-hhc=http.hhc 
