/* type entries, generated by maketypes.awk */

  { "GdkImlibImage", &GTK_TYPE_GDK_IMLIB_IMAGE,
    GTK_TYPE_BOXED, NULL },
  { "GtkCanvasPoints", &GTK_TYPE_CANVAS_POINTS,
    GTK_TYPE_BOXED, NULL },
