# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

#
# The targets
#


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/gtk-canvas
pkglibdir = $(libdir)/gtk-canvas
pkgincludedir = $(includedir)/gtk-canvas

top_builddir = ..

ACLOCAL = aclocal -I macros
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux
target_triplet = i686-pc-linux-gnu
AS = @AS@
AUDIOFILE_CFLAGS = @AUDIOFILE_CFLAGS@
AUDIOFILE_CONFIG = @AUDIOFILE_CONFIG@
AUDIOFILE_LIBS = @AUDIOFILE_LIBS@
AWK = gawk
CATALOGS = @CATALOGS@
CATOBJEXT = @CATOBJEXT@
CC = gcc
DATADIRNAME = @DATADIRNAME@
DLLTOOL = @DLLTOOL@
DL_LIB = -ldl
ESD_CFLAGS = @ESD_CFLAGS@
ESD_CONFIG = @ESD_CONFIG@
ESD_LIBS = @ESD_LIBS@
GDK_IMLIB_CFLAGS = -I/usr/include/gtk-1.2 -I/usr/include/glib-1.2 -I/usr/lib/glib/include -I/usr/X11R6/include -I/usr/X11R6/include
GDK_IMLIB_LIBS = -L/usr/lib -lgdk_imlib -L/usr/lib -L/usr/X11R6/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXi -lXext -lX11 -lm
GENCAT = @GENCAT@
GLIB_CFLAGS = -I/usr/lib/glib/include -I/usr/X11R6/include
GLIB_LIBS = -L/usr/lib -lglib
GMOFILES = @GMOFILES@
GMSGFMT = @GMSGFMT@
GTKDOC = false
GTK_CANVAS_IDLDIR = 
GTK_CANVAS_INCLUDEDIR = 
GTK_CANVAS_LIBDIR = 
GTK_CANVAS_LIBS = -lgtk-canvas -lart_lgpl -L/usr/lib -lgdk_imlib -L/usr/lib -L/usr/X11R6/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXi -lXext -lX11 -lm -L/usr/lib -L/usr/X11R6/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXi -lXext -lX11 -lm
GTK_CFLAGS = -I/usr/include/gtk-1.2 -I/usr/include/glib-1.2 -I/usr/lib/glib/include -I/usr/X11R6/include
GTK_CONFIG = /usr/bin/gtk-config
GTK_LIBS = -L/usr/lib -L/usr/X11R6/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXi -lXext -lX11 -lm
GT_NO = @GT_NO@
GT_YES = @GT_YES@
HAVE_GTK_DOC = 
IMLIB_CFLAGS = @IMLIB_CFLAGS@
IMLIB_CONFIG = /usr/bin/imlib-config
IMLIB_LIBS = @IMLIB_LIBS@
INCLUDE_LOCALE_H = @INCLUDE_LOCALE_H@
INDENT = indent
INSTOBJEXT = @INSTOBJEXT@
INTLDEPS = @INTLDEPS@
INTLLIBS = @INTLLIBS@
INTLOBJS = @INTLOBJS@
LIBGTK_CANVAS_LIBS = -L/usr/lib -lgdk_imlib -L/usr/lib -L/usr/X11R6/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXi -lXext -lX11 -lm -L/usr/lib -L/usr/X11R6/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXi -lXext -lX11 -lm
LIBOBJS = @LIBOBJS@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIBOBJS = @LTLIBOBJS@
MAINT = #
MAKEINFO = makeinfo
MKINSTALLDIRS = @MKINSTALLDIRS@
NSL_LIBS = 
OBJDUMP = @OBJDUMP@
ORBIT_CFLAGS = @ORBIT_CFLAGS@
ORBIT_CONFIG = @ORBIT_CONFIG@
ORBIT_IDL = @ORBIT_IDL@
ORBIT_LIBS = @ORBIT_LIBS@
PACKAGE = gtk-canvas
PERL = perl
POFILES = @POFILES@
POSUB = @POSUB@
PTHREAD_LIB = @PTHREAD_LIB@
RANLIB = ranlib
REBUILD = 
USE_INCLUDED_LIBINTL = @USE_INCLUDED_LIBINTL@
USE_NLS = @USE_NLS@
VERSION = 0.1
XPM_LIBS = -lXpm
cflags_set = @cflags_set@
cxxflags_set = @cxxflags_set@
l = @l@
need_gnome_support = @need_gnome_support@

lib_LTLIBRARIES = libgtk-canvas.la

#
# Install location for header files
#
libgtkcanvasincludedir = $(includedir)/gtk-canvas

INCLUDES = -I.. -I$(srcdir)/.. 	-I$(includedir) $(GDK_IMLIB_CFLAGS) 


EXTRA_HEADERS = 

libgtk_canvas_la_SOURCES =  	gtk-canvas.c				gtk-canvas-image.c			gtk-canvas-init.c			gtk-canvas-load.c			gtk-canvas-line.c			gtk-canvas-rect-ellipse.c		gtk-canvas-polygon.c			gtk-canvas-text.c			gtk-canvas-types.c               	gtk-canvas-util.c			gtk-canvas-widget.c


gtk_canvas_headers =  	gtk-canvas.h				gtk-canvas-defs.h			gtk-canvas-image.h			gtk-canvas-init.h			gtk-canvas-line.h			gtk-canvas-load.h			gtk-canvas-rect-ellipse.h		gtk-canvas-polygon.h			gtk-canvas-text.h			gtk-canvas-types.h			gtk-canvas-util.h			gtk-canvas-widget.h


libgtkcanvasinclude_HEADERS =  	$(gtk_canvas_headers)		gtk-canvastypebuiltins.h


BUILT_SOURCES =  	gtk-canvastypebuiltins.h			gtk-canvastypebuiltins_evals.c		gtk-canvastypebuiltins_ids.c			gtk-canvastypebuiltins_vars.c


#######################

EXTRA_DIST =  	AUTHORS						gtk-canvas.defs 					maketypes.awk					makeenums.pl					gtk-canvas-boxed.defs				gtk-canvastypebuiltins_vars.c			gtk-canvastypebuiltins_ids.c				gtk-canvastypebuiltins_evals.c


libgtk_canvas_la_LDFLAGS = -version-info 1:1:0 -rpath $(libdir)
libgtk_canvas_la_LIBADD = $(LIBGTK_CANVAS_LIBS)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(lib_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS =  -I/usr/include/gtk-1.2 -I/usr/include/glib-1.2 -I/usr/lib/glib/include -I/usr/X11R6/include
LDFLAGS = 
LIBS = -lz -lm 
libgtk_canvas_la_DEPENDENCIES = 
libgtk_canvas_la_OBJECTS =  gtk-canvas.lo gtk-canvas-image.lo \
gtk-canvas-init.lo gtk-canvas-load.lo gtk-canvas-line.lo \
gtk-canvas-rect-ellipse.lo gtk-canvas-polygon.lo gtk-canvas-text.lo \
gtk-canvas-types.lo gtk-canvas-util.lo gtk-canvas-widget.lo
CFLAGS = -g -O2
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(libgtkcanvasinclude_HEADERS)

DIST_COMMON =  AUTHORS ChangeLog Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libgtk_canvas_la_SOURCES)
OBJECTS = $(libgtk_canvas_la_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps gtk-canvas/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libgtk-canvas.la: $(libgtk_canvas_la_OBJECTS) $(libgtk_canvas_la_DEPENDENCIES)
	$(LINK) -rpath $(libdir) $(libgtk_canvas_la_LDFLAGS) $(libgtk_canvas_la_OBJECTS) $(libgtk_canvas_la_LIBADD) $(LIBS)

install-libgtkcanvasincludeHEADERS: $(libgtkcanvasinclude_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libgtkcanvasincludedir)
	@list='$(libgtkcanvasinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(libgtkcanvasincludedir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(libgtkcanvasincludedir)/$$p; \
	done

uninstall-libgtkcanvasincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(libgtkcanvasinclude_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(libgtkcanvasincludedir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = gtk-canvas

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-libLTLIBRARIES
install-exec: install-exec-am

install-data-am: install-libgtkcanvasincludeHEADERS
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-libLTLIBRARIES \
		uninstall-libgtkcanvasincludeHEADERS
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(libdir) \
		$(DESTDIR)$(libgtkcanvasincludedir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
mostlyclean-am:  mostlyclean-libLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-libLTLIBRARIES clean-compile clean-libtool clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-libLTLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-libLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-libLTLIBRARIES distclean-libLTLIBRARIES \
clean-libLTLIBRARIES maintainer-clean-libLTLIBRARIES \
uninstall-libLTLIBRARIES install-libLTLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool uninstall-libgtkcanvasincludeHEADERS \
install-libgtkcanvasincludeHEADERS tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


# generate gnome.defs file from gnome-boxed.defs and *.h
gtk-canvas.defs:  makeenums.pl gtk-canvas-boxed.defs $(gtk_canvas_headers)
	cd $(srcdir) \
	&& $(PERL) makeenums.pl defs $(gtk_canvas_headers) > gd.tmp \
	&& cat gtk-canvas-boxed.defs >> gd.tmp \
	&& mv gd.tmp gtk-canvas.defs

# generate type identifier header (GTK_TYPE_WIDGET_FLAGS)
gtk-canvastypebuiltins.h:  gtk-canvas.defs maketypes.awk
	cd $(srcdir) \
	&& LC_COLLATE=C $(AWK) -f maketypes.awk gtk-canvas.defs macros > gtb.tmp \
	&& mv gtb.tmp gtk-canvastypebuiltins.h

# generate type identifier variables (GTK_TYPE_WIDGET_FLAGS)
gtk-canvastypebuiltins_vars.c:  gtk-canvas.defs maketypes.awk
	cd $(srcdir) \
	&& LC_COLLATE=C $(AWK) -f maketypes.awk gtk-canvas.defs variables > gtbv.tmp \
	&& mv gtbv.tmp gtk-canvastypebuiltins_vars.c

# generate type entries for type-id registration
gtk-canvastypebuiltins_ids.c:  gtk-canvas.defs maketypes.awk
	cd $(srcdir) \
	&& LC_COLLATE=C $(AWK) -f maketypes.awk gtk-canvas.defs entries > gtbi.tmp \
	&& mv gtbi.tmp gtk-canvastypebuiltins_ids.c

# generate enum value arrays
gtk-canvastypebuiltins_evals.c:  makeenums.pl gtk-canvas.defs
	cd $(srcdir) \
	&& $(PERL) makeenums.pl arrays $(gtk_canvas_headers) > gtbe.tmp \
	&& mv gtbe.tmp gtk-canvastypebuiltins_evals.c

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
