#!/bin/sh
#
# Author:
#   Leif Kornstaedt <kornstae@ps.uni-sb.de>
#
# Copyright:
#   Leif Kornstaedt, 1998
#
# Last change:
#   $Date$ by $Author$
#   $Revision$
#
# This file is part of Mozart, an implementation of Oz 3:
#   $MOZARTURL$
#
# See the file "LICENSE" or
#   $LICENSEURL$
# for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL
# WARRANTIES.
#

: ${OZHOME=/usr/local/oz}
: ${OZDOC_ELISP_PATH=$OZHOME/share/elisp}

ELISP=''
for w in `echo $OZDOC_ELISP_PATH | sed 's/:/ /g'`; do
    ELISP="-L $w $ELISP"
done

exec emacs --batch $ELISP -l oz.elc -l ozdoc.elc -f ozdoc-fontify $*
