#!/bin/sh

if [ $# -ne 2 ]
then
    echo usage: `basename $0` \<input file\> \<output file\> 1>&2
    exit 2
fi

infile=$1
outfile=$2

giftopnm $infile | pnmscale -ysize 50 | ppmquant 256 | ppmtogif > $outfile
