#!/bin/sh

if [ $# -lt 1 -o $# -gt 2 ]
then
    echo usage: `basename $0` \<input file\> [\<output file\>] 1>&2
    exit 2
fi

infile=$1

if [ $# -eq 1 ]
then
    outfile=`basename $infile .tex`.gif
else
    outfile=$2
fi

tmpdir=/tmp/ps2gif.$$
mkdir $tmpdir
cp $infile $tmpdir/x.tex

(cd $tmpdir

latex x 1>&2 || exit 1
dvips x.dvi -o x.ps 1>&2

(cat x.ps; echo quit) |
gs -q -dNOPAUSE \
-dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r102 \
-sDEVICE=ppmraw -sOutputFile=x.ppm - 1>&2

pnmcrop < x.ppm | ppmtogif) > $outfile

echo Wrote $outfile 1>&2

rm -rf $tmpdir

exit 0
