#!/bin/sh
#
# Author:
#   Leif Kornstaedt <kornstae@ps.uni-sb.de>
#   Tobias Mueller <tmueller@ps.uni-sb.de>
#
# Contributor:   
#
# Copyright:
#   Leif Kornstaedt, 1998
#
# Last change:
#   $Date$ by $Author$
#   $Revision$
#
# This file is part of Mozart, an implementation of Oz 3:
#   $MOZARTURL$
#
# See the file "LICENSE" or
#   $LICENSEURL$
# for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL
# WARRANTIES.
#

if [ $# -lt 1 -o $# -gt 2 ]
then
    echo usage: `basename $0` \<input file\> [\<output file\>] 1>&2
    exit 2
fi

infile=$1

if [ $# -eq 1 ]
then
    outfile=`basename $infile .eps`.gif
else
    outfile=$2
fi

(cat $infile; echo quit) |
gs -q -dNOPAUSE \
-dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r102 \
-sDEVICE=ppmraw -sOutputFile=x.ppm - 1>&2

pnmcrop < x.ppm | ppmtogif > $outfile

echo Wrote $outfile 1>&2

rm -rf $tmpdir

exit 0
