#!/bin/sh

set -x

TK=tk4.2
TCL=tcl7.6

TCLHOME=/project/ps/soft/$TCL

############################################################

cd $TCL/unix
rm -rf dltest
make -k distclean
./configure --prefix=/project/ps/soft/$TCL --enable-gcc
make

cd ../../$TK/unix
rm -rf dltest
make -k distclean
./configure --prefix=/project/ps/soft/$TCL --enable-gcc
make

cd ../..

LIBDIR=$TCLHOME/platform/`ozplatform`
mkdir -p $LIBDIR/lib
cp $TCL/unix/libtcl7*6.a $LIBDIR/lib/libtcl.a
cp $TK/unix/libtk4*2.a $LIBDIR/lib/libtk.a
ranlib $LIBDIR/lib/*.a

mkdir -p $TCLHOME/include
cp $TCL/generic/tcl.h $TK/generic/tk.h $TCLHOME/include
