$cmode='dyn';

%builtins_all =
(
    #* OS interface

    'getDir'            => { in  => ['+virtualString'],
                             out => ['+[string]'],
                             BI  => unix_getDir,
                             module=>'os',
                             native => OK,
                             native => true},

    'stat'              => { in  => ['+virtualString'],
                             out => ['+record'],
                             BI  => unix_stat,
                             module=>'os',
                             native => true},

    'chDir'             => { in  => ['+virtualString'],
                             out => [],
                             BI  => unix_chDir,
                             module=>'os',
                             native => true},

    'getCWD'            => { in  => [],
                             out => ['+atom'],
                             BI  => unix_getCWD,
                             module=>'os',
                             native => true},

    'open'              => { in  => ['+virtualString','+[atom]','+[atom]'],
                             out => ['+int'],
                             BI  => unix_open,
                             module=>'os',
                             native => true},

    'fileDesc'  => { in  => ['+atom'],
                             out => ['+int'],
                             BI  => unix_fileDesc,
                             module=>'os',
                             native => true},

    'close'             => { in  => ['+int'],
                             out => [],
                             BI  => unix_close,
                             module=>'os',
                             native => true},

    'write'             => { in  => ['+int','+virtualString'],
                             out => ['+value'],
                             BI  => unix_write,
                             module=>'os',
                             native => true},

    'read'              => { in  => ['+int','+int','value','value','int'],
                             out => [],
                             BI  => unix_read,
                             module=>'os',
                             native => true},

    'lSeek'             => { in  => ['+int','+int','+atom'],
                             out => ['+int'],
                             BI  => unix_lSeek,
                             module=>'os',
                             native => true},

    'unlink'            => { in  => ['+virtualString'],
                             out => [],
                             BI  => unix_unlink,
                             module=>'os',
                             native => true},

    'readSelect'        => { in  => ['+int'],
                             out => [],
                             BI  => unix_readSelect,
                             module=>'os',
                             native => true},

    'writeSelect'       => { in  => ['+int'],
                             out => [],
                             BI  => unix_writeSelect,
                             module=>'os',
                             native => true},

    'acceptSelect'      => { in  => ['+int'],
                             out => [],
                             BI  => unix_acceptSelect,
                             module=>'os',
                             native => true},

    'deSelect'  => { in  => ['+int'],
                             out => [],
                             BI  => unix_deSelect,
                             module=>'os',
                             native => true},

    'system'            => { in  => ['+virtualString'],
                             out => ['+int'],
                             BI  => unix_system,
                             module=>'os',
                             native => true},

    'getEnv'            => { in  => ['+virtualString'],
                             out => ['+value'],
                             BI  => unix_getEnv,
                             module=>'os',
                             native => true},

    'putEnv'            => { in  => ['+virtualString','+virtualString'],
                             out => [],
                             BI  => unix_putEnv,
                             module=>'os',
                             native => true},

    'time'              => { in  => [],
                             out => ['+int'],
                             BI  => unix_time,
                             module=>'os',
                             native => true},

    'gmTime'            => { in  => [],
                             out => ['+record'],
                             BI  => unix_gmTime,
                             module=>'os',
                             native => true},

    'localTime' => { in  => [],
                             out => ['+record'],
                             BI  => unix_localTime,
                             module=>'os',
                             native => true},

    'srand'             => { in  => ['+int'],
                             out => [],
                             BI  => unix_srand,
                             module=>'os',
                             native => true},

    'rand'              => { in  => [],
                             out => ['+int'],
                             BI  => unix_rand,
                             module=>'os',
                             native => true},

    'randLimits'        => { in  => [],
                             out => ['+int','+int'],
                             BI  => unix_randLimits,
                             module=>'os',
                             native => true},

    'socket'            => { in  => ['+atom','+atom','+virtualString'],
                             out => ['+int'],
                             BI  => unix_socket,
                             module=>'os',
                             native => true},

    'bind'              => { in  => ['+int','+int'],
                             out => [],
                             BI  => unix_bindInet,
                             module=>'os',
                             native => true},

    'listen'            => { in  => ['+int','+int'],
                             out => [],
                             BI  => unix_listen,
                             module=>'os',
                             native => true},

    'connect'   => { in  => ['+int','+virtualString','+int'],
                             out => [],
                             BI  => unix_connectInet,
                             module=>'os',
                             native => true},

    'accept'            => { in  => ['+int'],
                             out => ['+int','+string','+int'],
                             BI  => unix_acceptInet,
                             module=>'os',
                             native => true},

    'shutDown'  => { in  => ['+int','+int'],
                             out => [],
                             BI  => unix_shutDown,
                             doesNotReturn=>1,
                             module=>'os',
                             native => true},

    'send'              => { in  => ['+int','+virtualString','+[atom]'],
                             out => ['+value'],
                             BI  => unix_send,
                             module=>'os',
                             native => true},

    'sendTo'            => { in  => ['+int','+virtualString','+[atom]',
                                     '+virtualString','+int'],
                             out => ['+value'],
                             BI  => unix_sendToInet,
                             module=>'os',
                             native => true},

    'receiveFrom'       => { in  => ['+int','+int','+[atom]','value','value'],
                             out => ['+string','+int','+int'],
                             BI  => unix_receiveFromInet,
                             module=>'os',
                             native => true},

    'getSockName'       => { in  => ['+int'],
                             out => ['+int'],
                             BI  => unix_getSockName,
                             module=>'os',
                             native => true},

    'getHostByName'     => { in  => ['+virtualString'],
                             out => ['+record'],
                             BI  => unix_getHostByName,
                             module=>'os',
                             native => true},

    'pipe'              => { in  => ['+virtualString','value'],
                             out => ['+int','+int#int'],
                             BI  => unix_pipe,
                             module=>'os',
                             native => true},

    'tmpnam'            => { in  => [],
                             out => ['+string'],
                             BI  => unix_tmpnam,
                             module=>'os',
                             native => true},

    'wait'              => { in  => [],
                             out => ['+int','+int'],
                             BI  => unix_wait,
                             module=>'os',
                             native => true},

    'getServByName'     => { in  => ['+virtualString','+virtualString'],
                             out => ['+int'],
                             BI  => unix_getServByName,
                             module=>'os',
                             native => true},

    'uName'             => { in  => [],
                             out => ['+record'],
                             BI  => unix_uName,
                             module=>'os',
                             native => true},

    'getpwnam'  => { in  => ['+virtualString'],
                             out => ['+record'],
                             BI  => unix_getpwnam,
                             module=>'os',
                             native => true},

 );
