#define NOPRAGMA

#ifdef __GNUC__
#pragma interface

#pragma implementation "actor.hh"
#pragma implementation "alarm.hh"
#pragma implementation "am.hh"
#pragma implementation "assemble.hh"
#pragma implementation "assreg.hh"
#pragma implementation "board.hh"
#pragma implementation "builtins.hh"
#pragma implementation "cell.hh"
#pragma implementation "codearea.hh"
#pragma implementation "constter.hh"
#pragma implementation "debug.hh"
#pragma implementation "dllist.hh"
#pragma implementation "dllstack.hh"
#pragma implementation "error.hh"
#pragma implementation "fdbool.hh"
#pragma implementation "fdgeneri.hh"
#pragma implementation "fdgennln.hh"
#pragma implementation "fdgenvar.hh"
#pragma implementation "fdhook.hh"
#pragma implementation "fdprofil.hh"
#pragma implementation "genvar.hh"
#pragma implementation "hashtbl.hh"
#pragma implementation "indexing.hh"
#pragma implementation "mem.hh"
#pragma implementation "misc.hh"
#pragma implementation "objects.hh"
#pragma implementation "special.hh"
#pragma implementation "stack.hh"
#pragma implementation "statisti.hh"
#pragma implementation "suspensi.hh"
#pragma implementation "system.hh"
#pragma implementation "tagged.hh"
#pragma implementation "taskstk.hh"
#pragma implementation "term.hh"
#pragma implementation "thread.hh"
#pragma implementation "trail.hh"
#pragma implementation "types.hh"
#pragma implementation "unify.hh"
#pragma implementation "verbose.hh"
#endif

#include "actor.cc"
#include "alarm.cc"
#include "am.cc"
#include "assemble.cc"
#include "assreg.cc"
#include "board.cc"
#include "builtins.cc"
#include "cell.cc"
#include "codearea.cc"
#include "constter.cc"
#include "debug.cc"
#include "dllist.cc"
#include "dllstack.cc"
#include "error.cc"
#include "fdbool.cc"
#include "fdgeneri.cc"
#include "fdgennln.cc"
#include "fdgenvar.cc"
#include "fdhook.cc"
#include "fdprofil.cc"
#include "genvar.cc"
#include "hashtbl.cc"
#include "indexing.cc"
#include "mem.cc"
#include "misc.cc"
#include "objects.cc"
#include "special.cc"
#include "stack.cc"
#include "statisti.cc"
#include "suspensi.cc"
#include "system.cc"
#include "tagged.cc"
#include "taskstk.cc"
#include "term.cc"
#include "thread.cc"
#include "trail.cc"
#include "types.cc"
#include "unify.cc"
#include "verbose.cc"
